### ISSUE TITLE
Web application delay on mobile devices.

### ISSUE THREAD

**Issue by bugz8** [bugz8/bugzpianokit#1]
I would like someone to **help** me on my web application I just created.

When I click on any button on the application it should be able to play a sound immediatly, **works fine on laptop**.
But when I press buttons on a **mobile it has a delay** to be able to play the sound.

If someone could help me with my **first web application** it would be great!

**Comment by Abde-Ssamade** [comment]
try adding keyx.preload='auto' for each one

**Comment by bugz8** [comment]
> 

can you identy what do you mean by "each one"? are speaking of html or css or js and are you also speaking of classes? I'm not quite sure.

**Comment by Abde-Ssamade** [comment]
I mean for each case in makesound(key) function in the index.js file add keyX.preload='auto'

**Comment by bugz8** [comment]
I just tested that it still delaying on mobile.
